version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    environment:
      - REDIS_URL=redis://redis:6379

  redis:
    container_name: redis
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - "6379:6379"

