openapi: 3.0.3
servers:
  - url: http://localhost:8080
    description: Local server

info:
  title: Brazilian Municipality Search
  description: Search for brazilian municipalities within a given polygon. Utilizes the Redis Search 7.2 GEOSHAPE API to search for polygons within a given area.
  version: 1.0.0

paths:
  /search:
    post:
      tags:
        - Municipio
      description: Search for Brazilian Municipality in a given polygon
      summary: Search for Brazilian Municipality
      operationId: searchPolygons
      requestBody:
        description: polygon
        required: true
        content:
          application/json:
            schema:
              title: polygon
              allOf:
                - $ref: "#/components/schemas/Feature"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MunicipioFeature"

  /municipio:
    post:
      tags:
        - Municipio
      description: Add a new municipio to the database
      summary: Add a new municipio
      operationId: addMunicipio
      requestBody:
        description: municipio
        required: true
        content:
          application/json:
            schema:
              title: Municipio Data
              allOf:
                - $ref: "#/components/schemas/MunicipioFeature"
             
      responses:
        "204":
          description: "Successfully added municipality"

components:
  schemas:
    "GeoJsonObject":
      description: >
        GeoJSon object
        The coordinate reference system for all GeoJSON coordinates is a
        geographic coordinate reference system, using the World Geodetic System
        1984 (WGS 84) datum, with longitude and latitude units of decimal
        degrees.
        This is equivalent to the coordinate reference system identified by the
        Open Geospatial Consortium (OGC) URN
        An OPTIONAL third-position element SHALL be the height in meters above
        or below the WGS 84 reference ellipsoid.
        In the absence of elevation values, applications sensitive to height or
        depth SHOULD interpret positions as being at local ground or sea level.
      externalDocs:
        url: "https://tools.ietf.org/html/rfc7946#section-3"
      type: object
      properties:
        "type":
          type: string
          enum:
            - Feature
            - FeatureCollection
            - Point
            - MultiPoint
            - LineString
            - MultiLineString
            - Polygon
            - MultiPolygon
            - GeometryCollection
        "bbox":
          description: >
            A GeoJSON object MAY have a member named "bbox" to include
            information on the coordinate range for its Geometries, Features, or
            FeatureCollections. The value of the bbox member MUST be an array of
            length 2*n where n is the number of dimensions represented in the
            contained geometries, with all axes of the most southwesterly point
            followed by all axes of the more northeasterly point. The axes order
            of a bbox follows the axes order of geometries.
          type: array
          items:
            type: number
      required:
        - type
      discriminator:
        propertyName: type

     'Geometry':
      description: >
        Abstract type for all GeoJSon object except Feature and
        FeatureCollection
      externalDocs:
        url: 'https://tools.ietf.org/html/rfc7946#section-3'
      allOf:
      - $ref: '#/components/schemas/GeoJsonObject'
      - type: object
        properties:
          'type':
            type: string
            enum:
            - Polygon
            - MultiPolygon

        required:
        - type
        discriminator:
          propertyName: type

    "Feature":
      description: GeoJSon 'Feature' object
      externalDocs:
        url: "https://tools.ietf.org/html/rfc7946#section-3.2"
      allOf:
        - $ref: "#/components/schemas/GeoJsonObject"
        - type: object
          required:
            - geometry
            - properties
          properties:
            "geometry":
              allOf:
                - $ref: "#/components/schemas/Geometry"
            "properties":
              type: object
              nullable: true
            "id":
              oneOf:
                - type: number
                - type: string

    "MunicipioFeature": 
      description: GeoJson Municipio Feature
      allOf:
        - $ref: "#/components/schemas/Feature"
        - type: object
          properties:
            "properties":
              allOf:
                - $ref: "#/components/schemas/MunicipioPropeties"
            "geometry":
              allOf:
                - $ref: "#/components/schemas/Geometry"

    "MunicipioPropeties": 
      description: Municipio Geojson Properties
      type: object
      properties:
        CD_MUN:
          type: string
          description: IBGE code
        NM_MUN:
          type: string
          description: Municipality name
        SIGLA_UF:
          type: string
          description: State name
        AREA_KM2:
          type: number
          format: double
          description: Area in square kilometers
        POPULATION:
          type: number
          format: uint32
          description: Population
